### ISSUE TITLE
`check_delta` function - working example 

### ISSUE THREAD

**Issue by UGuntupalli** [sandialabs/pecos#66]
Hello @kaklise , 
         I am trying to understand the intent and actual functioning of the `check_delta` function in the monitoring module. Here is an example that I put together: 

```python 
import pandas as pd
from pecos import monitoring

# Constants
UPPER_LIMIT_RANGE_FILTER = 1.2
LOWER_LIMIT_RANGE_FILTER = 0.5

# Create a random data frame
df = pd.DataFrame(data=[["2015-01-01 00:00:00", -0.76, 2, 2, 1.2],
                        ["2015-01-01 01:00:00", -0.73, 2, 4, 1.1],
                        ["2015-01-01 02:00:00", -0.71, 2, 4, 1.1],
                        ["2015-01-01 03:00:00", -0.68, 2, 32, 1.1],
                        ["2015-01-01 04:00:00", -0.65, 2, 2, 1.0]],
                  columns=['DateTime', 'column1', 'column2', 'column3', 'column4'])

# Set the index
df["DateTime"] = pd.to_datetime(df["DateTime"])
df.set_index("DateTime", inplace=True)

# Run delta flag
flags = pd.DataFrame()
for station in df.columns:
    rating = 2.5
    dead_jump_flag_check = monitoring.check_delta(
        data=df[[station]],
        bound=[LOWER_LIMIT_RANGE_FILTER * rating,
               UPPER_LIMIT_RANGE_FILTER * rating],
        key=None,
        window=3600,
        direction=None,
        min_failures=1
    )
    if flags.empty:
        flags = dead_jump_flag_check['mask']
    else:
        flags = pd.merge(left=flags, right=dead_jump_flag_check['mask'], on="DateTime")
print(flags)
```

My interpretation of the existing functionality here doesn't line up with what I am seeing in the example. The function should be flagging stuck data or abrupt changes. In the description of the function, the difference between max and min values within a rolling window is used for flagging it. 

In the above example, I am using window=3600 and min_failures=1, so even if one timestamp fails the condition, the flag should be triggered. I would appreciate if you can explain the following: 

1. What are the max and min values (delta) within a rolling window when the rolling window is 1 hour in hourly data ? Are the bound values even used in this calculation ? 
2. Looking at the example data set which is a dummy data set, looking at column 2 and column 3, I would think both of them should trigger the flag, however the result does not make sense to me. Here is the result: 

```python 
                     column1  column2  column3  column4
DateTime                                               
2015-01-01 00:00:00     True     True     True     True
2015-01-01 01:00:00    False    False    False    False
2015-01-01 02:00:00    False    False    False    False
2015-01-01 03:00:00    False    False    False    False
2015-01-01 04:00:00    False    False    False    False
```

- Why is row 1 flagged ? 
- Why are column 2 and column 3 not being flagged despite having stuck values and values that jump around ? 

     Would appreciate some clarity.. 

Best 
Uday

**Comment by kaklise** [comment]
The min, max, and delta values are computed using a rolling window with closed intervals.  When the rolling window is 1 hour in hourly data the subsequent data point is used to compute delta.  For example, the original, min, max, and delta values are listed below.  The first entry is NaN since it falls within the window.  That entry will always result in a mask value of True since it can't be tested.

Original data
```
                     column1  column2  column3  column4
DateTime                                               
2015-01-01 00:00:00    -0.76        2        2      1.2
2015-01-01 01:00:00    -0.73        2        4      1.1
2015-01-01 02:00:00    -0.71        2        4      1.1
2015-01-01 03:00:00    -0.68        2       32      1.1
2015-01-01 04:00:00    -0.65        2        2      1.0
```
Min value
```
                     column1  column2  column3  column4
DateTime                                               
2015-01-01 00:00:00      NaN      NaN      NaN      NaN
2015-01-01 01:00:00    -0.76      2.0      2.0      1.1
2015-01-01 02:00:00    -0.73      2.0      4.0      1.1
2015-01-01 03:00:00    -0.71      2.0      4.0      1.1
2015-01-01 04:00:00    -0.68      2.0      2.0      1.0
```
Max value
```
                     column1  column2  column3  column4
DateTime                                               
2015-01-01 00:00:00      NaN      NaN      NaN      NaN
2015-01-01 01:00:00    -0.73      2.0      4.0      1.2
2015-01-01 02:00:00    -0.71      2.0      4.0      1.1
2015-01-01 03:00:00    -0.68      2.0     32.0      1.1
2015-01-01 04:00:00    -0.65      2.0     32.0      1.1
```
Delta
```
                     column1  column2  column3  column4
DateTime                                               
2015-01-01 00:00:00      NaN      NaN      NaN      NaN
2015-01-01 01:00:00     0.03      0.0      2.0      0.1
2015-01-01 02:00:00     0.02      0.0      0.0      0.0
2015-01-01 03:00:00     0.03      0.0     28.0      0.0
2015-01-01 04:00:00     0.03      0.0     30.0      0.1
```
The bounds are then applied to the delta values to identify data points that are less than the lower bound and data points that are greater than the upper bound.  This function includes a post processing step that ensures that the actual data points involved in the min and max are flagged.  This becomes more apparent when using a window that is larger than your time interval.

In the example you provided, the lower bound is 1.25 and the upper bound is 3.  That means that every value in delta is flagged except the delta value 2.0 (column3 at 1:00).  However, the postprocessing step flags that data point as well since that is the start of the stagnant reading (original data in column3 at 1:00 and 2:00 are both 4).

When trying to identify both dead sensor readings and abrupt changes, I often call check_delta function twice.  This helps create the mask you need for both conditions.  Either way, I think the test results will help clarify.  In this case, column3 is involved both stagnant (delta < lower bound) and abrupt changes (delta > upper bound).  I create the following test results by running the check_delta function on all columns (instead of using a loop).

```
dead_jump_flag_check = monitoring.check_delta(
    data=df,
    bound=[LOWER_LIMIT_RANGE_FILTER * rating,
           UPPER_LIMIT_RANGE_FILTER * rating],
    key=None,
    window=3600,
    direction=None,
    min_failures=1
)

print(dead_jump_flag_check['test_results'])

	Variable Name	Start Time	End Time	Timesteps	Error Flag
0	column1	2015-01-01 01:00:00	2015-01-01 04:00:00	4	Delta < lower bound, 1.25
1	column2	2015-01-01 01:00:00	2015-01-01 04:00:00	4	Delta < lower bound, 1.25
2	column3	2015-01-01 01:00:00	2015-01-01 02:00:00	2	Delta < lower bound, 1.25
3	column4	2015-01-01 01:00:00	2015-01-01 04:00:00	4	Delta < lower bound, 1.25
4	column3	2015-01-01 02:00:00	2015-01-01 04:00:00	3	Delta > upper bound, 3.0
```

**Comment by UGuntupalli** [comment]
@kaklise ,
          Thank you for the explanation. Two things I was unable to understand are: 
1. What do you mean by applying the function repeatedly ? Can you please provide an example of how that can be done ? 
2. One of the things that I always try to do and I believe ```pecos``` is great at facilitating is when a mask is generated, try and avoid altering the shape from the original data set . Is that not possible with the ```check_delta``` function ?

**Comment by kaklise** [comment]
Your original example used a loop (``for station in df.columns``) to run check_delta on each column of data.  In my response, I called check_delta once and used the entire data set.  This keeps the mask the same shape as the data.
