### ISSUE TITLE
Divide by zero error in check_timestamp

### ISSUE THREAD

**Issue by rpauly18** [sandialabs/pecos#70]
When trying to apply the check_timestamp function to high frequency data (i.e. 50kHz which equals 0.00002s) the function produces a zero division error. I have uploaded a sample of data so you can try and reproduce the error if you need. Let me know if there is any way I can help de-bug this issue. Thanks!

![Screen Shot 2021-06-09 at 7 24 54 AM](https://user-images.githubusercontent.com/50752018/121363013-cbfe9780-c8f3-11eb-806e-e48a0acceb8b.png)

[50khz_data.csv](https://github.com/sandialabs/pecos/files/6624031/50khz_data.csv)

**Comment by kaklise** [comment]
Pecos supports timestamps down to millisecond resolution, we could probably set that a little lower but the issue is that floating point numbers are not exact and you start to run into precession errors.  This is especially important when trying to determine if you have timestamps at an exact frequency.  It looks like your data has a frequency of 0.001s with duplicate timestamps.
